### PR TITLE
Cleanup proj < 8 pinning

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akrherz** [comment]
OK, this PR is green for your consideration.

**Comment by alexander-buerger-met-no** [comment]
It will not build with proj 8, see #21.

**Comment by akrherz** [comment]
Hi @alexander-buerger-met-no , that was the point of my PR, to correct the pinning to reflect as such :)

**Comment by alexander-buerger-met-no** [comment]
Sorry, I got confused with all the proj 8 nagging.

I do not understand very well which packages should be in `build`, `host` and `run`. My impression was that `build` should have build system packages (like `ninja`, `pkg-config`, …), while libraries used by the package should be in `host` and that actual versions of these libraries would be copied into `run` during package build. Did I misunderstand?

**Comment by akrherz** [comment]
> My impression was that `build` should have build system packages

I believe that is correct, I have modified by PR accordingly.

**Comment by alexander-buerger-met-no** [comment]
Thanks.

**Pull request merged**
